### ISSUE TITLE
Error with BottomNavigation styles

### ISSUE THREAD

**Issue by PlaidPhantom** [halfnelson/svelte-native#101]
Starting from a fresh template (locked to tns-core-modules 6.2.1, per #100), I get an error whenever I switch tabs in a BottomNavigation element. Here's my App.svelte:

```html
<page>
    <actionBar title="Svelte Native App" />
    <bottomNavigation>
        <tabStrip>
            <tabStripItem>
                <label text="Albums" />
            </tabStripItem>
            <tabStripItem>
                <label text="Artists" />
            </tabStripItem>
        </tabStrip>

        <tabContentItem>
            <label text="here's tab 1!" />
        </tabContentItem>
        <tabContentItem>
            <label text="here's tab 2!" />
        </tabContentItem>
    </bottomNavigation>
</page>

<script>
</script>
```

Here's the error in the console when run with `tns run android`:

```
JS: Error: Failed to apply property [color] with value [#30bcff] to TabStripItem(8). Error: undefined is not a valid file or resource.
JS:     at Function.push.../node_modules/@nativescript/core/image-source/image-source.js.ImageSource.fromFileOrResourceSync (file:///node_modules/@nativescript/core/image-source/image-source.js:118:0)
JS:     at BottomNavigation.push.../node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js.BottomNavigation.getIcon (file:///node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js:476:0)
JS:     at BottomNavigation.push.../node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js.BottomNavigation.setTabBarIconColor (file:///node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js:535:0)
JS:     at Object.callback (file:///node_modules/@nativescript/core/ui/tab-navigation-base/tab-strip-item/tab-strip-item.js:92:0)
JS:     at Style.push.../node_modules/@nativescript/core/data/observable/observable.js.Observable.notify (file:///node_modules/@nativescript/core/data/observable/observable.js:110:0)
JS:     at Style.<anonymous...
JS: Error: Failed to apply property [color] with value [#262626] to TabStripItem(6). Error: undefined is not a valid file or resource.
JS:     at Function.push.../node_modules/@nativescript/core/image-source/image-source.js.ImageSource.fromFileOrResourceSync (file:///node_modules/@nativescript/core/image-source/image-source.js:118:0)
JS:     at BottomNavigation.push.../node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js.BottomNavigation.getIcon (file:///node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js:476:0)
JS:     at BottomNavigation.push.../node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js.BottomNavigation.setTabBarIconColor (file:///node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js:535:0)
JS:     at Object.callback (file:///node_modules/@nativescript/core/ui/tab-navigation-base/tab-strip-item/tab-strip-item.js:92:0)
JS:     at Style.push.../node_modules/@nativescript/core/data/observable/observable.js.Observable.notify (file:///node_modules/@nativescript/core/data/observable/observable.js:110:0)
JS:     at Style.<anonymous...
```

**Comment by halfnelson** [comment]
thanks for this. This is  a known issue with the Nativescript implementation. The tabs and bottom navigation components are quite new and seem to have a few rough edges
https://github.com/NativeScript/NativeScript/issues/7902
