### ISSUE TITLE
Empty component causes error

### ISSUE THREAD

**Issue by RedHatter** [halfnelson/svelte-native#123]
Rendering a component with no content or only a script tag throws the following error.

```
An uncaught Exception occurred on "main" thread.
Unable to start activity ComponentInfo{com.eatthismuch.dev/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
TypeError: Cannot create property 'm' on boolean 'false'
StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eatthismuch.dev/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
TypeError: Cannot create property 'm' on boolean 'false'
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3760)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8147)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
TypeError: Cannot create property 'm' on boolean 'false'
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
	at android.app.Activity.performCreate(Activity.java:8066)
	at android.app.Activity.performCreate(Activity.java:8054)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
	... 11 more
```

For example see the following.

App.svelte
```
<script>
  import Empty from './Empty.svelte'
</script>

<page>
  <Empty />
</page>
```

Empty.svelte
```
<script>
  export let prop
</script>
```

This might seem unimportant as a component with no content is rare but they can be useful. E.g. to cause side effects.

**Comment by halfnelson** [comment]
Which versions are you running. I can run this on the Repl
https://svelte-native.technology/repl?version=3.19.2&gist=0ba088ec51ec64ee086133e32cf2f5b6

**Comment by halfnelson** [comment]
Tracked this down to an error in svelte-hot-loader. It has trouble creating a reload proxy for empty components

**Comment by halfnelson** [comment]
i'll open a ticket on that repo

**Comment by halfnelson** [comment]
The maintainer of the repo says this now works.

**Comment by RedHatter** [comment]
This is still an issue when dev mode is off. I have a PR open for svelte-hmr to fix it.
