### ISSUE TITLE
Error: PubNub call failed, check status for details

### ISSUE THREAD

**Issue by dina06** [halfnelson/svelte-native#137]
hi, when i try to excute this line-command "tns preview --bundle" , the qr code  appear and i scan it and i get this 
Preparing project...
Project successfully prepared (android)
Start sending initial files for device OPPO A3s (bb8bc545-bd86-4036-bc41-46a48ef0cf03).
Successfully sent initial files for device OPPO A3s (bb8bc545-bd86-4036-bc41-46a48ef0cf03).

but after that i get also this error
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\NIS\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\NIS\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\NIS\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\NIS\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\NIS\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\NIS\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

can someone help me to solve this issue ?

**Comment by halfnelson** [comment]
sounds like pubnub was blocked or down temporarily, probably a question for the nativescript folks if it is still happening
