### ISSUE TITLE
System.err: TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by beebase** [halfnelson/svelte-native#192]
Whenever I import this script into a Svelte component I get this error:
Does anyone recognize the what's causing this? 

`System.err: TypeError: Cannot read property 'slice' of undefined`

SCRIPT
```
import ApolloClient from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
import { WebSocketLink } from "apollo-link-ws";
import { split } from "apollo-link";
import { HttpLink } from "apollo-link-http";
import { getMainDefinition } from "apollo-utilities";

const headers = { "content-type": "application/json" };
const getHeaders = () => {
  return headers;
};

const cache = new InMemoryCache();

const wsLink = new WebSocketLink({
  uri: "ws://localhost:8080/v1/graphql",
  options: {
    reconnect: true,
    lazy: true,
    connectionParams: () => {
      return { headers: getHeaders() };
    },
  },
});

const httpLink = new HttpLink({
  uri: "http://localhost:8080/v1/graphql",
  headers: getHeaders(),
});

const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === "OperationDefinition" && operation === "subscription";
  },
  wsLink,
  httpLink
);

export const client = new ApolloClient({
  link,
  cache,
});

```

STACK

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'slice' of undefined
System.err: File: (file: node_modules/readable-stream/lib/_stream_writable.js:57:71)
System.err:
System.err: StackTrace:
System.err: (file: node_modules/readable-stream/lib/_stream_writable.js:57:71)
System.err:     at ../node_modules/readable-stream/lib/_stream_writable.js(file:///data/data/technology.sveltenative.template/files/app/vendor.js:107301:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/readable-stream/writable.js(file: node_modules/readable-stream/writable.js:2:15)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/stream-browserify/index.js(file: node_modules/stream-browserify/index.js:29:18)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/readable-stream/readable.js(file: node_modules/readable-stream/readable.js:1:13)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/hash-base/index.js(file: node_modules/hash-base/index.js:3:16)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/md5.js/index.js(file: node_modules/md5.js/index.js:3:15)     
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/evp_bytestokey/index.js(file: node_modules/evp_bytestokey/index.js:2:10)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse-asn1/fixProc.js(file: node_modules/parse-asn1/fixProc.js:5:10)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse-asn1/index.js(file: node_modules/parse-asn1/index.js:3:14)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/public-encrypt/publicEncrypt.js(file: node_modules/public-encrypt/publicEncrypt.js:1:16)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/public-encrypt/browser.js(file: node_modules/public-encrypt/browser.js:1:24)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/public-encrypt/index.js(file: node_modules/public-encrypt/index.js:3:11)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/crypto-browserify/index.js(file: node_modules/crypto-browserify/index.js:48:20)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/ws/lib/websocket.js(file: node_modules/ws/lib/websocket.js:4:15)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/ws/index.js(file: node_modules/ws/index.js:3:18)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/subscriptions-transport-ws/dist/server.js(file: node_modules/subscriptions-transport-ws/dist/server.js:4:16)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/subscriptions-transport-ws/dist/index.js(file: node_modules/subscriptions-transport-ws/dist/index.js:14:13)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/apollo-link-ws/lib/bundle.esm.js(file: node_modules/apollo-link-ws/lib/bundle.esm.js:1:0)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ./utils/graphqlclient.js(file: app/utils/graphqlclient.js:1:0)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:4392:81)
System.err:     at ./page/product/ProductCreate.svelte(file:///data/data/technology.sveltenative.template/files/app/bundle.js:4655:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:4936:92)
System.err:     at ./page/product/ProductList.svelte(file:///data/data/technology.sveltenative.template/files/app/bundle.js:5259:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:2014:90)
System.err:     at ./page/Main.svelte(file:///data/data/technology.sveltenative.template/files/app/bundle.js:2252:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:3002:75)
System.err:     at ./page/auth/SignIn.svelte(file:///data/data/technology.sveltenative.template/files/app/bundle.js:3232:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:75:82)
System.err:     at ./App.svelte(file:///data/data/technology.sveltenative.template/files/app/bundle.js:166:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file: app/app.ts:1:0)
System.err:     at ./app.ts(file:///data/data/technology.sveltenative.template/files/app/bundle.js:256:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:816:0)
System.err:     at checkDeferredModules(file: app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:2:57)System.err:     at require(:1:266)
```

PACKAGE.JSON

```
{
  "name": "tns-template-blank-svelte",
  "displayName": "Blank Svelte",
  "templateType": "App template",
  "author": "David Pershouse (https://github.com/halfnelson)",
  "version": "7.0.0",
  "main": "app.js",
  "description": "Blank template for Nativescript application using Svelte",
  "license": "Apache-2.0",
  "repository": "https://github.com/halfnelson/svelte-native-template",
  "dependencies": {
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.3.3",
    "@nativescript/webpack": "3.0.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "apollo-link-error": "^1.1.13",
    "apollo-link-http": "^1.5.17",
    "apollo-link-ws": "^1.0.20",
    "apollo-utilities": "^1.3.4",
    "graphql": "^15.4.0",
    "graphql-tag": "^2.11.0",
    "subscriptions-transport-ws": "^0.9.18",
    "svelte-native": "~0.9.1"
  },
  "devDependencies": {
    "@nativescript/android": "7.0.1",
    "svelte": "~3.24.1",
    "svelte-loader-hot": "~0.3.1",
    "svelte-native-preprocessor": "^0.2.0",
    "svelte-preprocess": "^4.0.8",
    "typescript": "~4.0.2"
  },
  "gitHead": "c06800e52ee1a184ea2dffd12a6702aaa43be4e3",
  "readme": "NativeScript Application"
}
```

**Comment by shirakaba** [comment]
```
System.err:     at ../node_modules/readable-stream/writable.js(file: node_modules/readable-stream/writable.js:2:15)
```

Could you copy-paste the contents around line 2 of `node_modules/readable-stream/writable.js`?
