### ISSUE TITLE
No known component for element radSideDrawer.

### ISSUE THREAD

**Issue by zeddrix** [halfnelson/svelte-native#255]
I want to put a drawer in my application. I just wanted to try it out at first as shown here in the docs: https://svelte-native.technology/docs#property-element

```
<radSideDrawer>
	<radSideDrawer.drawerContent>
		<stackLayout />
	</radSideDrawer.drawerContent>
	<radSideDrawer.mainContent>
		<stackLayout />
	</radSideDrawer.mainContent>
</radSideDrawer>
```

But I'm getting this error when doing this:

```
CONSOLE ERROR: [HMR][Svelte] Unrecoverable error in <LogInView>: next update will trigger a full reload
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: No known component for element radSideDrawer.
at
createElement(file: node_modules/svelte-native/dom/index.js:321:0)
at createElement(file: node_modules/svelte-native/dom/index.js:343:0)
at createElementNS(file: node_modules/svelte-native/dom/index.js:1256:0)
at create(file:///app/bundle.js:3528:29)
at create(file:///app/bundle.js:2827:35)
at create_component(file: node_modules/svelte/internal/index.mjs:1369:0)
at create(file:///app/bundle.js:3637:76)
at init(file: node_modules/svelte/internal/index.mjs:1461:0)
at LogInView(file:///app/bundle.js:3767:63)
at createProxiedComponent(file: node_modules/svelte-hmr/runtime/svelte-hooks.js:237:0)
at ProxyComponent(file: node_modules/svelte-hmr/runtime/proxy.js:196:34)
at Proxy<LogInView>(file: node_modules/svelte-hmr/runtime/proxy.js:255:0)
at resolveComponentElement(file: node_modules/svelte-native/dom/index.js:1313:0)
at navigate(file: node_modules/svelte-native/dom/index.js:1326:33)
at onLogInTap(file: app/App.svelte:11:36)
at (file: node_modules/svelte/internal/index.mjs:663:0)
at bubble(file: node_modules/svelte/internal/index.mjs:663:0)
at tap_handler(file:///app/bundle.js:392:65)
at handler.__wrapper(file: node_modules/svelte-native/dom/index.js:803:0<…>
```

I even tried doing this:

```
<script>
  import { onMount } from 'svelte'
  
  let drawer
  let drawerContent
  let mainContent
  
  onMount(() => {
	  drawer.nativeView.mainContent = mainContent.nativeView
	  drawer.nativeView.drawerContent = drawerContent.nativeView
  })
</script>

<radSideDrawer bind:this="{drawer}">
	<stackLayout bind:this="{drawerContent}" />
	<stackLayout bind:this="{mainContent}" />
</radSideDrawer>
```

But I'm still getting the same error. The docs only says this:
> The <radSideDrawer> component is part of the [Progress NativeScript UI](https://docs.nativescript.org/ui/professional-ui-components/SideDrawer/getting-started) package.

But the link to the [Progress NativeScript UI](https://docs.nativescript.org/ui/professional-ui-components/SideDrawer/getting-started) is not working either.

Am I missing something? What am I doing wrong here? This is one of the utilities—does it need setting up? If yes, how will I set it up to use this?

**Comment by uzarsalan** [comment]
You should register element first

https://github.com/halfnelson/svelte-native-nativescript-ui

**Comment by zeddrix** [comment]
Thanks a lot man!
