### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Vehmloewff** [halfnelson/svelte-native#55]
After scanning the QR code in the REPL, I got the following error:

```
2019-09-18 18:27:13.592 nsplaydev[1306:411826] ***** Fatal JavaScript exception - application has been terminated. ***** 2019-09-18 18:27:13.592 nsplaydev[1306:411826] Native stack trace: 1 0x1018b72fc NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool) 2 0x1018fc2a4 -[TNSRuntime executeModule:referredBy:] 3 0x1028a21f8 -[UIApplication(PlayLiveSync) swizzled_executeModule:] 4 0x100fbb420 5 0x20405abb4 <redacted> 2019-09-18 18:27:13.593 nsplaydev[1306:411826] JavaScript stack trace: 2019-09-18 18:27:13.593 nsplaydev[1306:411826] dispatch_dev(file:///app/app.js:1331:27) at create_fragment(file:///app/app.js:1446:14) at init(file:///app/app.js:1294:34) at App(file:///app/app.js:1480:7) at resolveComponentElement(file:///app/app.js:999:36) at navigate(file:///app/app.js:1012:60) at svelteNative(file:///app/app.js:1085:32) at start(file:///app/app.js:1486:17) at anonymous(file:///app/main.js:18:10) at evaluate([native code]) at moduleEvaluation([native code]) at promiseReactionJob([native code]) 2019-09-18 18:27:13.593 nsplaydev[1306:411826] JavaScript error: file:///app/app.js:1331:27: JS ERROR TypeError: document.dispatchEvent is not a function. (In 'document.dispatchEvent(custom_event(type, detail))', 'document.dispatchEvent' is undefined) 2019-09-18 18:27:13.594 nsplaydev[1306:411826] PlayLiveSync: Uncaught Exception 2019-09-18 18:27:13.594 nsplaydev[1306:411826] *** JavaScript call stack: ( ) 2019-09-18 18:27:13.594 nsplaydev[1306:411826] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: document.dispatchEvent is not a function. (In 'document.dispatchEvent(custom_event(type, detail))', 'document.dispatchEvent' is undefined) at dispatch_dev(file:///app/app.js:1331:27) at create_fragment(file:///app/app.js:1446:14) at init(file:///app/app.js:1294:34) at App(file:///app/app.js:1480:7) at resolveComponentElement(file:///app/app.js:999:36) at navigate(file:///app/app.js:1012:60) at svelteNative(file:///app/app.js:1085:32) at start(file:///app/app.js:1486:17) at anonymous(file:///app/main.js:18:10) at evaluate([native code]) at moduleEvaluation([native code]) at promiseReactionJob([native code]) ', reason: '(null)' *** First throw call stack: (0x204610ec4 0x2037e1a40 0x1018b7778 0x1018fc2a4 0x1028a21f8 0x100fbb420 0x20405abb4) libc++abi.dylib: terminating with uncaught exception of type NSException 2019-09-18 18:27:13.595 nsplaydev[1306:411826] PlayLiveSync: Uncaught Exception
```

I did not change the code in the REPL.  Just scanned the QR and got the error.

Am I doing something wrong?

**Comment by halfnelson** [comment]
Nothing you are doing wrong, The REPL defaults to the latest version of Svelte and it looks like version 3.12.1 is not compatible with the svelte-native version in the repl. (yet).
If you change the url of the REPL to an earlier version it should work again: eg https://svelte-native.technology/repl?version=3.9.0&example=hello-world

**Comment by halfnelson** [comment]
This should be fixed now, I released a new version of svelte native and website with the fix

**Comment by Vehmloewff** [comment]
Thanks!
