### ISSUE TITLE
Error using `onMount` in App.svelte

### ISSUE THREAD

**Issue by PlaidPhantom** [halfnelson/svelte-native#81]
Hi, I'm getting a strange error whenever I add an `onMount` callback to my main svelte component. I'm able to duplicate this both in my own app and with a newly-cloned template just by adding the `onMount` function.  I've forked the template repo to demonstrate: https://github.com/PlaidPhantom/svelte-native-template. All I need to do to get the error is clone that repo, run `npm install`, and run `tns run android`.

`tns --version` returns 6.1.2.

I haven't ruled out user error; I'm new to most of this tech stack, but from what I've read so far I think this should work.  Also, I'm pretty sure onMount worked when i was experimenting with Svelte Native a few months ago.

Here's the error I get when i run my app on the device:

```
An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: Function called outside component initialization
File: (file:///data/data/technology.sveltenative.template/files/app/vendor.js:3300:4)

StackTrace: 
	get_current_component(file:///data/data/technology.sveltenative.template/files/app/vendor.js:5537:15)
	at onMount(file:///data/data/technology.sveltenative.template/files/app/vendor.js:5544:5)
	at instance(file:///data/data/technology.sveltenative.template/files/app/bundle.js:134:59)
	at init(file:///data/data/technology.sveltenative.template/files/app/vendor.js:7999:11)
	at App(file:///data/data/technology.sveltenative.template/files/app/bundle.js:150:63)
	at createProxiedComponent(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3632:8)
	at ProxyComponent(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3276:86)
	at Proxy<App>(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3338:5)
	at resolveComponentElement(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4755:24)
	at navigate(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4768:37)
	at svelteNative(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4913:28)
	at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:252:67)
	at ./app.ts(file:///data/data/technology.sveltenative.template/files/app/bundle.js:265:30)
	at __webpack_require__(file:///data/data/technology.sveltenative.template/files/app/runtime.js:751:30)
	at checkDeferredModules(file:///data/data/technology.sveltenative.template/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/technology.sveltenative.template/files/app/runtime.js:31:19)
	at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:2:57)
	at require(:1:266)


Error: Function called outside component initialization

StackTrace:
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: Function called outside component initialization
File: (file:///data/data/technology.sveltenative.template/files/app/vendor.js:3300:4)

StackTrace: 
	get_current_component(file:///data/data/technology.sveltenative.template/files/app/vendor.js:5537:15)
	at onMount(file:///data/data/technology.sveltenative.template/files/app/vendor.js:5544:5)
	at instance(file:///data/data/technology.sveltenative.template/files/app/bundle.js:134:59)
	at init(file:///data/data/technology.sveltenative.template/files/app/vendor.js:7999:11)
	at App(file:///data/data/technology.sveltenative.template/files/app/bundle.js:150:63)
	at createProxiedComponent(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3632:8)
	at ProxyComponent(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3276:86)
	at Proxy<App>(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3338:5)
	at resolveComponentElement(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4755:24)
	at navigate(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4768:37)
	at svelteNative(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4913:28)
	at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:252:67)
	at ./app.ts(file:///data/data/technology.sveltenative.template/files/app/bundle.js:265:30)
	at __webpack_require__(file:///data/data/technology.sveltenative.template/files/app/runtime.js:751:30)
	at checkDeferredModules(file:///data/data/technology.sveltenative.template/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/technology.sveltenative.template/files/app/runtime.js:31:19)
	at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:2:57)
	at require(:1:266)


Error: Function called outside component initialization
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.tns.NativeScriptException: Error calling module function 
Error: Function called outside component initialization
File: (file:///data/data/technology.sveltenative.template/files/app/vendor.js:3300:4)

StackTrace: 
	get_current_component(file:///data/data/technology.sveltenative.template/files/app/vendor.js:5537:15)
	at onMount(file:///data/data/technology.sveltenative.template/files/app/vendor.js:5544:5)
	at instance(file:///data/data/technology.sveltenative.template/files/app/bundle.js:134:59)
	at init(file:///data/data/technology.sveltenative.template/files/app/vendor.js:7999:11)
	at App(file:///data/data/technology.sveltenative.template/files/app/bundle.js:150:63)
	at createProxiedComponent(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3632:8)
	at ProxyComponent(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3276:86)
	at Proxy<App>(file:///data/data/technology.sveltenative.template/files/app/vendor.js:3338:5)
	at resolveComponentElement(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4755:24)
	at navigate(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4768:37)
	at svelteNative(file:///data/data/technology.sveltenative.template/files/app/vendor.js:4913:28)
	at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:252:67)
	at ./app.ts(file:///data/data/technology.sveltenative.template/files/app/bundle.js:265:30)
	at __webpack_require__(file:///data/data/technology.sveltenative.template/files/app/runtime.js:751:30)
	at checkDeferredModules(file:///data/data/technology.sveltenative.template/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/technology.sveltenative.template/files/app/runtime.js:31:19)
	at (file:///data/data/technology.sveltenative.template/files/app/bundle.js:2:57)
	at require(:1:266)


Error: Function called outside component initialization
	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:662)
	at com.tns.Runtime.run(Runtime.java:654)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
	... 8 more

```

**Comment by halfnelson** [comment]
Thanks for the report. It looks like this was due to the existence of index.mjs and index.js files in svelte and svelte-native, webpack was preferring the .js file while typescript was preferring the .mjs file, this was leading to two copies of svelte/internals being included which breaks things!

I have updated the template to have webpack prefer .mjs when available and this has resolved the problem.
